bamboo_agent_configuration = __import__("bamboo-agent-configuration")

BambooAgentController = bamboo_agent_configuration.BambooAgentController
BambooAgent = bamboo_agent_configuration.BambooAgent
Method = bamboo_agent_configuration.Method
Response = bamboo_agent_configuration.Response
Request = bamboo_agent_configuration.Request
HttpRequestHandler = bamboo_agent_configuration.HttpRequestHandler
timeout = bamboo_agent_configuration.timeout
BambooAgentError = bamboo_agent_configuration.BambooAgentError
ServerCommunicationError = bamboo_agent_configuration.ServerCommunicationError
MissingUuid = bamboo_agent_configuration.MissingUuid
SelfRecoverableBambooAgentError = (
    bamboo_agent_configuration.SelfRecoverableBambooAgentError
)
AssignmentNotFound = bamboo_agent_configuration.AssignmentNotFound
