name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: install requirements
        shell: bash
        run: pip install -r dev-requirements.txt
      - name: run black
        shell: bash
        run: black --check .
      - name: build collection
        shell: bash
        run: ./build.sh
      - name: upload collection package
        uses: actions/upload-artifact@v1
        with:
          name: collection
          path: release
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: install ansible
        shell: bash
        run: pip install ansible==6.3.0
      - name: unit and integration tests
        shell: bash
        run: python tests
  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: install ansible
        shell: bash
        run: pip install ansible==6.3.0
      - name: acceptance tests
        shell: bash
        run: tests/acceptance_tests.sh
      - name: upload test results
        uses: actions/upload-artifact@v1
        with:
          name: acceptance-test-results
          path: tests/env/results
        if: always()
  
